### ISSUE TITLE
hugectr memory pool is empty 

### ISSUE THREAD

**Issue by kimharo** [triton-inference-server/hugectr_backend#38]
hello. i tested hugectr backend again. and I use perf_analyzer 

I use merlin-inference:22:03 and v100 hugectr backend use 28G gpu. so there is 4G gpu memory remain
![스크린샷 2022-04-08 오후 1 18 02](https://user-images.githubusercontent.com/4977729/162361558-9846e35d-1e7f-421d-984e-409be5097c88.png)

when I tested with perf_analyzer concurrency 17 then throughput rapidly drop and hugectr log with memory pool is empty. how can I fix this?

```bash
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1906.57 infer/sec, latency 520 usec
Concurrency: 5, throughput: 7677.62 infer/sec, latency 647 usec
Concurrency: 9, throughput: 11505.2 infer/sec, latency 778 usec
Concurrency: 13, throughput: 12422.1 infer/sec, latency 1042 usec
Concurrency: 17, throughput: 3247.32 infer/sec, latency 5232 usec
Concurrency: 21, throughput: 764.767 infer/sec, latency 27540 usec
Concurrency: 25, throughput: 240.7 infer/sec, latency 103849 usec
Concurrency: 29, throughput: 217.05 infer/sec, latency 133800 usec

```

```bash
[HCTR][02:36:36][WARNING][RK0][tid #139898459779072]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139898459779072]: memory pool is empty
[HCTR][02:36:36][INFO][RK0][EC insert #10]: *****Insert embedding cache of model meb on device 4*****
[HCTR][02:36:36][WARNING][RK0][tid #139898459779072]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139898459779072]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
[HCTR][02:36:36][WARNING][RK0][tid #139916302344192]: memory pool is empty
```

and I want change huge ctr log option. I already use triton_server option --log-verbose=0 and --log-info=false. but hugectr log display info log. I can I change hugectr log option?

**Comment by yingcanw** [comment]
@kimharo Thanks for your feedback. Sorry for the late reply.

> when I tested with perf_analyzer concurrency 17 then throughput rapidly drop and hugectr log with memory pool is empty. how can I fix this?

First of all, the throughput is not completely determined by the number of concurrency. The key factor should be the number of model instances launched by Trition(https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups).  You can imagine that if there are 10 concurrent requests, but only one model instance is used for inference, then the 10th request must wait until the first 9 requests are completed before it can be responded, which is degenerate into serial executions queue, but the throughput is calculated based on the average latency of all concurrent requests, so when there are insufficient model instances, the higher concurrency concurrency, the lower the throughput.

Second, because hugectr backend supports asynchronous insertion of missing keys (when the actual hit rate is higher than the user-defined threshold), high concurrent requests will inevitably exhaust the memory pool. The size of the memory pool is determined by **num_of_worker_buffer_in_pool** in ps json config file. You can avoid memory pool exhaustion by increasing the size of the memory pool (such as 2 times the number of model instance), or disable asynchronous updates (set the **hit_rate_threshold** to greater than 1)

> and I want change huge ctr log option. I already use triton_server option --log-verbose=0 and --log-info=false. but hugectr log display info log. I can I change hugectr log option?

Third, the hugectr backend log is not controlled by Triton and cannot be closed. We will provide a detailed introduction of each configuration item of the hugectr backend in the next release.

**Comment by kimharo** [comment]
thanks. 
I tested a100. instance_group: 16 and num_of_worker_buffer_in_pool : 64. then "memory pool is empty" is gone. 

but another message shown in log. and server crash.

```txt
[HCTR][04:25:17][INFO][RK0][tid #139232614006784]: *****Insert embedding cache of model meb on device 6*****
[HCTR][04:25:17][DEBUG][RK0][tid #140023131262976]: ParallelHashMap backend. Table: hctr_et.meb.sparse_embedding1. Fetched 79 / 122 values.
[HCTR][04:25:17][INFO][RK0][tid #140023131262976]: Parameter server lookup of 79 / 122 embeddings took 129 us.
[HCTR][04:25:17][INFO][RK0][tid #139232614006784]: [HCTR][04:25:17][INFO][RK0][tid #139227647950848]: *****Insert embedding cache of model meb on device 5*****
Looking up 96 embeddings (each with 15 values)...
[HCTR][04:25:17][INFO][RK0][tid #139227647950848]: Looking up 180 embeddings (each with 15 values)...
 0# 0x000055ACED5F9299 in tritonserver
 1# 0x00007F93BF132210 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007F93BF27A9E1 in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# HugeCTR::embedding_cache<long long>::look_up(void const*, std::vector<unsigned long, std::allocator<unsigned long> > const&, float*, HugeCTR::MemoryBlock*, std::vector<CUstream_st*, std::allocator<CUstream_st*> > const&, float) in /usr/local/hugectr/lib/libhugectr_inference.so
 4# HugeCTR::InferenceSession::predict(float*, void*, int*, float*, int) in /usr/local/hugectr/lib/libhugectr_inference.so
 5# 0x00007F93B412329D in /usr/local/hugectr/backends/hugectr/libtriton_hugectr.so
 6# TRITONBACKEND_ModelInstanceExecute in /usr/local/hugectr/backends/hugectr/libtriton_hugectr.so
 7# 0x00007F93BFCD4F9A in /opt/tritonserver/bin/../lib/libtritonserver.so
 8# 0x00007F93BFCD56B7 in /opt/tritonserver/bin/../lib/libtritonserver.so
 9# 0x00007F93BFB6D1A1 in /opt/tritonserver/bin/../lib/libtritonserver.so
10# 0x00007F93BFCCF527 in /opt/tritonserver/bin/../lib/libtritonserver.so
11# 0x00007F93BF520DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
12# 0x00007F93BF99E609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
13# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

[HCTR][04:25:17][DEBUG][RK0][tid #139232614006784]: ParallelHashMap backend. Table: hctr_et.meb.sparse_embedding1. Fetched 76 / 96 values.
[HCTR][04:25:17][INFO][RK0][tid #139232614006784]: Parameter server lookup of 76 / 96 embeddings took 119 us.
[HCTR][04:25:17][INFO][RK0][tid #139239064850432]: *****Insert embedding cache of model meb on device 5*****
[HCTR][04:25:17][INFO][RK0][tid #139239064850432]: Looking up 181 embeddings (each with 15 values)...
[HCTR][04:25:17][INFO][RK0][tid #139237647171584]: *****Insert embedding cache of model meb on device 7*****
[HCTR][04:25:17][INFO][RK0][tid #139237647171584]: Looking up 142 embeddings (each with 15 values)...
```

and cpu usage so high. that time almost 70 ~ 80%. but gpu usage is 15~20%.

**Comment by yingcanw** [comment]
> I tested a100. instance_group: 16 and num_of_worker_buffer_in_pool : 64. then "memory pool is empty" is gone.

See from the log that there are at least 7 devices? Each device launches 16 concurrent model instances and initializes 64 workers in the buffer pool . Refer to the previous issue(https://github.com/triton-inference-server/hugectr_backend/issues/35), although the batch size is not large, but the maximum number of categorical features(`cat_feature_num` in config.pbtxt) required for each sample is very large, because the size of the worker buffer pool is also pre-allocated according to the batch size and the maximum number of categorical features (the worker buffer pool is mainly used for the GPU cache to temporarily store keys/vectors when looking up embedding keys). In addition, it can be seen from the log that the number of embedding keys looked up from CPU and latency are within expectations, so it is recommended to reduce the size of the `num_of_worker_buffer_in_pool` and try to disable the asynchronous insertion mode, which could be solve this issue.

**Comment by kimharo** [comment]
when I tested instance_group and num_of_worker_buffer_in_pool. many case server crash. I using merlin-inference:22:03. I tested hugectr backend with 10 million requests.

tested server a100.
instance_group: 8, num_of_worker_buffer_in_pool: 16 -> work well.
instance_group: 12, num_of_worker_buffer_in_pool: 16 -> server crash  with signal(11).
instance_group: 12, num_of_worker_buffer_in_pool: 16 hit ratio : 1.1 -> server crash with signal(11).
instance_group:16, num_of_worker_buffer_in_pool: 64 -> server crash with signal(11).
instance_group:16, num_of_worker_buffer_in_pool: 32 -> server crash with signal(11).

many case server crash  so I difficult to test.

**Comment by yingcanw** [comment]
@kimharo 
Just follow the steps below and disable the asynchronous insertion mode to see if the crash still occurs.
1.  Set the `hit_rate_threshold` to greater than 1 
2. Set `num_of_worker_buffer_in_pool` equal to the number of triton instances deployed in each device. If possible, just launch one triton instance on single device and set `num_of_worker_buffer_in_pool=1`

**Comment by kimharo** [comment]
we tested merlin-inference:22.04 version. it works well. no crash!!! thanks

we config 

1. hist_rate_threshold: 1.1
2. instance_group : 4, num_of_worker_buffer_in_pool 8
