### ISSUE TITLE
how to put all embedding volume into gpu embedding cache?

### ISSUE THREAD

**Issue by kimharo** [triton-inference-server/hugectr_backend#39]
* image: merlin-inference:22.03
* machine: v100
* request: 10 milion request (repeat)

we tested hugectr backend. 10 million request repeat(1 epoch) ~repeat(2 epoch) ...repeat(50 epoch) then cpu usage is continuous lower. it may be because gpu embedding cache. more embedding insert gpu embedding cache then cpu usage, rps improve.
![스크린샷 2022-04-21 오후 6 35 51](https://user-images.githubusercontent.com/4977729/165268244-c56970ce-f0cc-4f71-a41d-e0a65ac33028.png)

 so we make small volume to fit in gpu cache. v100 gpu memory is 32GB. so we make small embedding volume 19GB.
this volume fit in gpu cache. so we expect huge cpu usage, rps  improvement first epoch. but  result is same.

 in first epoch, cpu usage still high 70~80%...... if gpu embedding cache loading all volume in initial time. then cpu usage can be very low. 

 this is our ps.json. how can we load all volume to gpu embedding cache? we already set gpucacheper 1.0. but useless

```json
{
    "supportlonglong":"true",
    "volatile_db": {
            "type":"parallel_hash_map",
            "initial_cache_rate":1.0,
            "max_get_batch_size": 100000,
            "max_set_batch_size": 100000
    },
    "models":[
        {
            "model":"meb",
            "supportlonglong":true,
            "num_of_worker_buffer_in_pool":"8",
            "num_of_refresher_buffer_in_pool":"1",
            "deployed_device_list":[0, 1, 2, 3, 4, 5, 6, 7],
            "max_batch_size":100,
            "default_value_for_each_table":[0.0],
            "hit_rate_threshold":"1.1",
            "gpucacheper":"1.0",
            "gpucache":"true",
            "cache_refresh_percentage_per_iteration":0.0,
            "sparse_files":["/infer/models/video-meb-bmtest-v3/1/meb0_sparse_0.model"],
            "dense_file":"/infer/models/video-meb-bmtest-v3/1/meb_dense_0.model",
            "network_file":"/infer/models/video-meb-bmtest-v3/1/meb.json"
        }
    ]
}
```

**Comment by yingcanw** [comment]
If you need to check the performance of the GPU cache, you should check the usage of the GPU instead of the cpu. From your description, I understand that your model can be completely loaded into the GPU memory. Since the GPU cache is empty at initialization, a warmup stage is required, that is, gradually load hot embedding keys from cpu into gpu cache according to inference requests, so CPU usage is gradually decreased.

**Comment by kimharo** [comment]
yes. so we want to find gpu_cache parameter like volatile_db's **inital_cache_rate**. does it exists such parameter in gpu_cache ? or not?

**Comment by yingcanw** [comment]
The GPU cache does not support direct loading part of embedding tables at initialization. This is because the data shift exists between the training data and the real inference requests. Preloading the embedded table into the cache causes higher overhead of hot data exchange during the warm-up phase than directly inserting the missing keys into an empty GPU cache, which is also consistent with the definition of hardware cache.

**Comment by yingcanw** [comment]
EC will support similar feature as volatile_db's `inital_cache_rate` in the future release.

**Comment by kimharo** [comment]
@yingcanw 

thanks!!!
