### ISSUE TITLE
how to update model weight (triton_server) after continue training!!

### ISSUE THREAD

**Issue by kimharo** [triton-inference-server/hugectr_backend#44]
hello. we test continue training. 

we follow this example. https://github.com/triton-inference-server/hugectr_backend/blob/v3.5/samples/hierarchical_deployment/hps_e2e_demo/Continuous_Training.ipynb 

so we tested this sample with our simple dataset. first we use Kafka and training. and we config Kafka setting in triton ps.json. it work well.

* hugectr training log
![스크린샷 2022-05-31 오후 2 58 50](https://user-images.githubusercontent.com/4977729/171103044-dda67d70-44d5-4a4d-ad1b-abcf028a6200.png)

* triton log
![스크린샷 2022-05-31 오후 2 56 03](https://user-images.githubusercontent.com/4977729/171102629-9bf0df1a-8630-4089-8005-f508cb5be1ee.png)

but we can't find how to update model weight triton server after update embedding.

we found other way. that is use load api. but load api load model weight and embedding too. in case. we don't need use Kafka. just update model, embedding. but we can't find example how to use load api.

![스크린샷 2022-05-31 오후 3 01 14](https://user-images.githubusercontent.com/4977729/171103309-5da96133-837c-4e3f-83cc-46f4c17f000c.png)

so we found two triton embedding update scenario

1. continue training with Kafka, triton. but just update embedding. (we want know how to update model weight after that or freeze_dense?)

2. continue training no Kafka, triton. use load api and load model weight and update embedding.

**Comment by yingcanw** [comment]
@kimharo Sorry for the late reply.

> continue training with Kafka, triton. but just update embedding. (we want know how to update model weight after that or freeze_dense?)

You can still use the Load API provided by Triton.  In order to avoid the embedding table from being updated repeatedly as you mentioned, we provide a new configuration option **freeze_sparse**  in new release 22.06(v3.7), which is used to freeze the embedding table updating if you enable [HugeCTR Inference Hierarchical Parameter Server Online Update](https://github.com/triton-inference-server/hugectr_backend#hugectr-inference-hierarchical-parameter-server-online-update).  You can refer to [Update the deployed model online](https://github.com/triton-inference-server/hugectr_backend#model-repository-extension) part and [Triton_Update_Model.ipynb](https://github.com/triton-inference-server/hugectr_backend/blob/main/samples/hierarchical_deployment/hps_e2e_demo/Triton_Update_Model.ipynb) for more details.
